# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  gitea:
    image: docker.io/gitea/gitea:1.24.6-rootless@sha256:91f2b27e080739f0d19dba716c3214f17257c632cf762e545b44ca577e37052c
    ports:
    - 13000:13000
    volumes:
    - ./teststate/gitea-data:/var/lib/gitea
    - ./teststate/gitea-init:/var/lib/gitea-init
    - ./teststate/gitea-etc:/etc/gitea
    environment:
    - DISABLE_SSH=true
    entrypoint:
    - /bin/bash
    - -cex
    - |
      cp -av /var/lib/gitea-init/* /var/lib/gitea/
      chown -R 1000 /var/lib/gitea/*
      # crane config gitea/gitea:latest-rootless | jq -r '.config.Entrypoint | join(" ")'
      /usr/bin/dumb-init -- /usr/local/bin/docker-entrypoint.sh

# apitest
# APItest1
# http://localhost:13000/apitest/test1
# fa8ba4c74e7969bcf5be39e39ccc89ab8cb8e880
